#
#   using this file to place program setting
#   this file built for developers only
#


parameters:
    yard_ads.paginator_service: "knp_paginator" # you can use your own custome paginator service
    yard_ads.ads_service: "app.ads_service"
    yard_ads.specification_service: "app.specification_service"