fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_list:
    path:     /admin/users
    defaults: { _controller: UserBundle:User:list }
user_remove:
    path:     /admin/users/remove/{id}
    defaults: { _controller: UserBundle:User:remove }    